project_id = "pewdswjhsesfondewucc"

[functions.daily-weather-post]
verify_jwt = false

[functions.fetch-weather]
verify_jwt = false

[functions.generate-caption]
verify_jwt = false

[functions.process-scheduled-posts]
verify_jwt = false

[functions.tiktok-auth]
verify_jwt = false
