// Step handlers for the 4 pipeline job types.
//
// Implementation strategy (incremental):
// - The 4 types are real, separately retryable, observable jobs.
// - For now, `generate_content` chains through to `publish_post` by delegating
//   the heavy lifting to the existing `process-scheduled-posts` function via
//   a single internal call on the publish step. This lets us land the job
//   system end-to-end without rewriting 2000 lines of pipeline code.
// - Each handler can be replaced with native logic later without touching
//   the runner, scheduler, or dashboard.

import type { JobContext, JobHandler, JobStepResult, JobType } from "./job-runner.ts";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;

// ───────────────── generate_content ─────────────────
// Validates that a scheduled_post + city + weather settings exist.
// Output: { validated: true } — chains to generate_voice.
const generateContent: JobHandler = async ({ job, supabase, log }): Promise<JobStepResult> => {
  const scheduledPostId = job.scheduled_post_id;
  if (!scheduledPostId) {
    throw new Error("generate_content requires scheduled_post_id");
  }
  const { data: post, error } = await supabase
    .from("scheduled_posts")
    .select("id, user_id, city, platform, scheduled_at, include_voiceover, status")
    .eq("id", scheduledPostId)
    .maybeSingle();
  if (error) throw new Error(`Failed to load scheduled_post: ${error.message}`);
  if (!post) throw new Error(`scheduled_post ${scheduledPostId} not found`);
  if (post.status === "succeeded") {
    await log("Scheduled post already succeeded — skipping job chain");
    return { done: true };
  }
  await log("Content prerequisites validated", { city: post.city, platform: post.platform });

  return {
    output: {
      city: post.city,
      platform: post.platform,
      include_voiceover: post.include_voiceover,
    },
    next: { type: "generate_voice" },
  };
};

// ───────────────── generate_voice ─────────────────
// In v1: a no-op pass-through (voice generation lives inside the
// existing pipeline). The job exists so retries/observability work
// when we move voice out into its own step.
const generateVoice: JobHandler = async ({ job, log }): Promise<JobStepResult> => {
  const includeVoice = job.payload.include_voiceover === true;
  await log(includeVoice ? "Voice will be generated by publish step" : "No voiceover requested");
  return { next: { type: "render_video" } };
};

// ───────────────── render_video ─────────────────
// Same approach as generate_voice — placeholder until rendering is split out.
const renderVideo: JobHandler = async ({ log }): Promise<JobStepResult> => {
  await log("Render will be performed by publish step");
  return { next: { type: "publish_post" } };
};

// ───────────────── publish_post ─────────────────
// Delegates to the existing process-scheduled-posts function for ONE
// specific scheduled_post_id. This keeps proven logic working while
// the job system handles locking, retries, notifications, and timeline.
const publishPost: JobHandler = async ({ job, supabase, log }): Promise<JobStepResult> => {
  if (!job.scheduled_post_id) throw new Error("publish_post requires scheduled_post_id");

  const url = `${SUPABASE_URL}/functions/v1/process-scheduled-posts`;
  const res = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${SERVICE_ROLE}`,
      "apikey": SERVICE_ROLE,
    },
    body: JSON.stringify({
      scheduled_post_id: job.scheduled_post_id,
      source: "job_runner",
      job_id: job.id,
    }),
  });
  const text = await res.text();
  if (!res.ok) {
    throw new Error(`process-scheduled-posts returned ${res.status}: ${text.slice(0, 500)}`);
  }
  await log("Publish delegated to process-scheduled-posts", { status: res.status });

  // Verify the scheduled_post actually moved out of pending/processing
  const { data: post } = await supabase
    .from("scheduled_posts")
    .select("status, error_message")
    .eq("id", job.scheduled_post_id)
    .maybeSingle();
  if (post && (post.status === "failed" || post.status === "failed_precheck")) {
    throw new Error(`Scheduled post ended in ${post.status}: ${post.error_message ?? "unknown"}`);
  }
  return { output: { final_status: post?.status ?? "unknown" }, done: true };
};

export const handlers: Record<JobType, JobHandler> = {
  generate_content: generateContent,
  generate_voice: generateVoice,
  render_video: renderVideo,
  publish_post: publishPost,
};
