// Step handlers for the pipeline job types.
//
// Pipeline:
//   generate_content → generate_voice → render_video → publish_post → analyze_performance
//
// `generate_content` is also where the AUTONOMOUS LOOP closes: before the
// content is generated, it reads the last 3 `pipeline_reflections` for the
// city and injects them as recommendations + an `engine_state` flag
// ("optimized" if today's recipe matches a recent winner, "experiment" if
// we're deliberately trying something new).
//
// `analyze_performance` is the hidden 5th step — scheduled 24h after a
// successful publish — that fetches the published post's stats, compares
// them to the user's rolling average, and writes a `pipeline_reflections`
// row that future `generate_content` jobs will read from.

import type { JobContext, JobHandler, JobStepResult, JobType } from "./job-runner.ts";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;

// 24h delay between publish and the reflection step.
const REFLECTION_DELAY_SECONDS = 24 * 60 * 60;

// ───────────────── generate_content ─────────────────
const generateContent: JobHandler = async ({ job, supabase, log }): Promise<JobStepResult> => {
  const scheduledPostId = job.scheduled_post_id;
  if (!scheduledPostId) {
    throw new Error("generate_content requires scheduled_post_id");
  }
  const { data: post, error } = await supabase
    .from("scheduled_posts")
    .select("id, user_id, city, platform, scheduled_at, include_voiceover, status, debug_trace")
    .eq("id", scheduledPostId)
    .maybeSingle();
  if (error) throw new Error(`Failed to load scheduled_post: ${error.message}`);
  if (!post) throw new Error(`scheduled_post ${scheduledPostId} not found`);
  if (post.status === "succeeded") {
    await log("Scheduled post already succeeded — skipping job chain");
    return { done: true };
  }

  // ── AUTONOMOUS LOOP: read last 3 reflections for this city ──
  const { data: reflections } = await supabase
    .from("pipeline_reflections")
    .select("visual_style, voice_tone, hook_type, performance, views, user_avg_views, recommendation, created_at")
    .eq("user_id", job.user_id)
    .eq("city", post.city)
    .order("created_at", { ascending: false })
    .limit(3);

  const recipe = (post.debug_trace as any)?.ai_recipe ?? null;
  const reflectionList = (reflections ?? []) as any[];

  // engine_state: "optimized" if today's recipe matches any recent HIGH winner;
  //               "experiment" if it diverges from all recent records.
  let engineState: "optimized" | "experiment" = "experiment";
  let referenceJob: string | null = null;
  if (recipe && reflectionList.length > 0) {
    const winner = reflectionList.find(
      (r) =>
        r.performance === "high" &&
        (r.visual_style === recipe.visual_style ||
          r.voice_tone === recipe.voice_tone ||
          r.hook_type === recipe.hook_type),
    );
    if (winner) {
      engineState = "optimized";
      referenceJob = `${winner.visual_style}/${winner.voice_tone}`;
    }
  }

  // Build a short hint string for downstream caption/visual prompts.
  const hints = reflectionList.map((r) => {
    const tag = r.performance === "high" ? "✓" : r.performance === "low" ? "✗" : "•";
    return `${tag} ${r.visual_style ?? "?"}/${r.voice_tone ?? "?"}/${r.hook_type ?? "?"} → ${Math.round(r.views)} views (avg ${Math.round(r.user_avg_views)}). ${r.recommendation ?? ""}`.trim();
  });

  // Persist the engine state on the scheduled_post so the publish step + UI
  // can read it without re-querying reflections.
  const updatedTrace = {
    ...((post.debug_trace as any) ?? {}),
    engine_state: engineState,
    reflection_hints: hints,
    reference_job: referenceJob,
  };
  await supabase
    .from("scheduled_posts")
    .update({ debug_trace: updatedTrace })
    .eq("id", post.id);

  await log("Content prerequisites validated", {
    city: post.city,
    platform: post.platform,
    engine_state: engineState,
    reflections_used: hints.length,
  });

  return {
    output: {
      city: post.city,
      platform: post.platform,
      include_voiceover: post.include_voiceover,
      engine_state: engineState,
      reflection_hints: hints,
      reference_job: referenceJob,
    },
    next: { type: "generate_voice" },
  };
};

// ───────────────── generate_voice ─────────────────
const generateVoice: JobHandler = async ({ job, log }): Promise<JobStepResult> => {
  const includeVoice = job.payload.include_voiceover === true;
  await log(includeVoice ? "Voice will be generated by publish step" : "No voiceover requested");
  return { next: { type: "render_video" } };
};

// ───────────────── render_video ─────────────────
const renderVideo: JobHandler = async ({ log }): Promise<JobStepResult> => {
  await log("Render will be performed by publish step");
  return { next: { type: "publish_post" } };
};

// ───────────────── publish_post ─────────────────
const publishPost: JobHandler = async ({ job, supabase, log }): Promise<JobStepResult> => {
  if (!job.scheduled_post_id) throw new Error("publish_post requires scheduled_post_id");

  // Pre-flight: log the voice asset that will be used (and gate on it when
  // voiceover is required). Catches "silent video" bugs before we burn a render.
  const { data: preflight } = await supabase
    .from("scheduled_posts")
    .select("include_voiceover, voiceover_url, voice_status, city_id, slot, platform, user_id")
    .eq("id", job.scheduled_post_id)
    .maybeSingle();
  const voiceUrl = preflight?.voiceover_url ?? null;
  console.log(
    `[publish_post] job=${job.id} post=${job.scheduled_post_id} include_voiceover=${preflight?.include_voiceover === true} voice_url=${voiceUrl ? voiceUrl.split("?")[0] : "(none)"} voice_status=${preflight?.voice_status ?? "n/a"}`,
  );
  await log("Voice asset pre-flight", {
    include_voiceover: preflight?.include_voiceover === true,
    has_voice_url: !!voiceUrl,
    voice_status: preflight?.voice_status ?? null,
  });

  // ── PUBLISH LOCK (safety net for pipeline path) ──
  // process-scheduled-posts also acquires the lock, but acquiring here too
  // means a duplicate pipeline run short-circuits before delegating.
  if (preflight?.city_id && preflight?.platform) {
    const slot = preflight.slot || "adhoc";
    try {
      const { data: gotLock } = await supabase.rpc("acquire_publish_lock", {
        p_user: preflight.user_id ?? job.user_id,
        p_city_id: preflight.city_id,
        p_slot: slot,
        p_platform: preflight.platform,
        p_tz: null,
        p_scheduled_post_id: job.scheduled_post_id,
      });
      if (gotLock === false) {
        await log("Skipped — publish lock held (pipeline)", { slot, platform: preflight.platform });
        return { output: { skipped: "lock_held", slot, platform: preflight.platform }, done: true };
      }
    } catch (e) {
      console.warn(`[publish_post] lock rpc failed (continuing): ${(e as Error)?.message}`);
    }
  }


  const url = `${SUPABASE_URL}/functions/v1/process-scheduled-posts`;
  const res = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${SERVICE_ROLE}`,
      "apikey": SERVICE_ROLE,
    },
    body: JSON.stringify({
      scheduled_post_id: job.scheduled_post_id,
      source: "job_runner",
      job_id: job.id,
    }),
  });
  const text = await res.text();
  if (!res.ok) {
    throw new Error(`process-scheduled-posts returned ${res.status}: ${text.slice(0, 500)}`);
  }
  await log("Publish delegated to process-scheduled-posts", { status: res.status });

  const { data: post } = await supabase
    .from("scheduled_posts")
    .select("status, error_message, scheduled_at, platform, city, user_id")
    .eq("id", job.scheduled_post_id)
    .maybeSingle();

  const errMsg = post?.error_message ?? "";
  const isDeduped = /\[DEDUPED\]/i.test(errMsg);
  const authExpiredMatch = /\[AUTH_EXPIRED:([a-z]+)\]/i.exec(errMsg);

  // ── Soft-skip: dedup ──
  // Already posted within the dedup window — not an error, surface as info
  // and end the chain cleanly (no retry, no analyze_performance).
  if (isDeduped) {
    await log("Skipped — duplicate post within 60-min window", { city: post?.city, platform: post?.platform });
    await supabase.from("notifications").insert({
      user_id: job.user_id,
      title: `✅ Skipped — already posted to ${post?.city ?? "this city"} in last 60 min`,
      message: `${post?.platform ?? "Post"} for ${post?.city ?? "city"} was skipped because a successful post already exists.`,
      type: "info",
    });
    return { output: { skipped: "deduped", city: post?.city, platform: post?.platform }, done: true };
  }

  // ── Soft-skip: expired token ──
  // Token refresh failed — show a reconnect prompt and DO NOT count as a
  // failed pipeline step (no retry, no "Pipeline step failed" notification).
  if (authExpiredMatch) {
    const platform = authExpiredMatch[1];
    await log(`Skipped — ${platform} connection expired`, { city: post?.city, platform });
    await supabase.from("notifications").insert({
      user_id: job.user_id,
      title: `⚠️ ${platform.charAt(0).toUpperCase() + platform.slice(1)} (${post?.city ?? "city"}) connection expired`,
      message: `Reconnect in Settings → Social Connections to resume posting.`,
      type: "warning",
    });
    return { output: { skipped: "auth_expired", platform, city: post?.city }, done: true };
  }

  if (post && (post.status === "failed" || post.status === "failed_precheck")) {
    throw new Error(`publish_post FAILED — scheduled_post status=${post.status}: ${post.error_message ?? "unknown"}`);
  }

  // Belt-and-suspenders: even if scheduled_posts.status is "posted", verify
  // that at least one post_history row was actually created with status=success
  // AND has an external_id (videoId/postId). This catches false-positive
  // success when an upstream adapter returned ok without a real upload.
  // 60-min window to tolerate slow renders.
  const sinceIso = new Date(Date.now() - 60 * 60 * 1000).toISOString();
  const cityFull = (post?.city ?? "").trim();
  const cityShort = cityFull.split(",")[0].trim();
  let histQuery = supabase
    .from("post_history")
    .select("id, platform, status, external_id, error_message, created_at")
    .eq("user_id", job.user_id)
    .gte("created_at", sinceIso);
  // Loose city match: exact OR partial (handles "Gainesville" vs
  // "Gainesville, Florida" mismatches). Skip filter if no city known.
  if (cityShort) {
    histQuery = histQuery.or(`city.eq.${cityFull},city.ilike.%${cityShort}%`);
  }
  const { data: histories } = await histQuery
    .order("created_at", { ascending: false })
    .limit(20);
  const rows = histories ?? [];
  const successWithId = rows.find((r: any) => r.status === "success" && r.external_id);
  const anySuccess = rows.find((r: any) => r.status === "success");
  await log("Publish verification", {
    scheduled_post_status: post?.status ?? null,
    history_rows: rows.length,
    success_with_external_id: !!successWithId,
    platforms_attempted: rows.map((r: any) => `${r.platform}:${r.status}${r.external_id ? `(id=${r.external_id})` : ""}`),
    error_message: post?.error_message ?? null,
  });

  let verification: "post_history" | "scheduled_post_status" = "post_history";
  if (!successWithId) {
    const reason = anySuccess
      ? `publish_post FAILED — platform reported success but returned no external id. error=${post?.error_message ?? "unknown"}`
      : `publish_post FAILED — no successful platform upload. error=${post?.error_message ?? "unknown"}`;
    await log("⚠ post_history verification found no row with external_id — checking scheduled_post status directly", { rows: rows.length });
    if (post?.status !== "posted") {
      throw new Error(reason);
    }
    await log("scheduled_post.status=posted — treating as success despite missing post_history row", {});
    verification = "scheduled_post_status";
  }

  // ── Schedule the hidden 5th step 24h from now ──
  return {
    output: {
      final_status: post?.status ?? "unknown",
      verification,
      published_platforms: rows.filter((r: any) => r.status === "success").map((r: any) => r.platform),
      external_ids: rows
        .filter((r: any) => r.status === "success" && r.external_id)
        .map((r: any) => ({ platform: r.platform, id: r.external_id })),
    },
    next: { type: "analyze_performance", delaySeconds: REFLECTION_DELAY_SECONDS },
  };
};

// ───────────────── analyze_performance ─────────────────
// Fetches the most recent post_history + post_analytics for this scheduled
// post, compares views to the user's rolling 30-day average, and writes a
// pipeline_reflections row that future generate_content jobs will read.
const analyzePerformance: JobHandler = async ({ job, supabase, log }): Promise<JobStepResult> => {
  if (!job.scheduled_post_id) {
    await log("analyze_performance skipped — no scheduled_post_id");
    return { done: true };
  }

  const { data: sp } = await supabase
    .from("scheduled_posts")
    .select("id, user_id, city, scheduled_at, debug_trace")
    .eq("id", job.scheduled_post_id)
    .maybeSingle();
  if (!sp) {
    await log("analyze_performance skipped — scheduled_post not found");
    return { done: true };
  }

  const recipe = (sp.debug_trace as any)?.ai_recipe ?? {};
  const visualStyle = recipe.visual_style ?? null;
  const voiceTone = recipe.voice_tone ?? null;
  const hookType = recipe.hook_type ?? null;

  // Find the post_history row created by process-scheduled-posts. We
  // correlate by user + city + a window around scheduled_at.
  const scheduledMs = new Date(sp.scheduled_at).getTime();
  const windowStart = new Date(scheduledMs - 30 * 60 * 1000).toISOString();
  const windowEnd = new Date(scheduledMs + 4 * 60 * 60 * 1000).toISOString();
  const { data: histories } = await supabase
    .from("post_history")
    .select("id, views_count, likes_count, comment_count, created_at, status")
    .eq("user_id", sp.user_id)
    .eq("city", sp.city)
    .gte("created_at", windowStart)
    .lte("created_at", windowEnd)
    .order("created_at", { ascending: false })
    .limit(3);

  const successHistory = (histories ?? []).find((h: any) => h.status === "success") ?? null;

  // Aggregate analytics from all platforms tied to this post.
  let views = successHistory?.views_count ?? 0;
  let engagement =
    (successHistory?.likes_count ?? 0) + (successHistory?.comment_count ?? 0);

  if (successHistory?.id) {
    const { data: analytics } = await supabase
      .from("post_analytics")
      .select("views, likes, comments, shares")
      .eq("post_id", successHistory.id);
    if (analytics && analytics.length > 0) {
      views = analytics.reduce((s: number, a: any) => s + (a.views ?? 0), 0);
      engagement = analytics.reduce(
        (s: number, a: any) => s + (a.likes ?? 0) + (a.comments ?? 0) + (a.shares ?? 0),
        0,
      );
    }
  }

  // Rolling 30-day average views for this user.
  const since = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString();
  const { data: avgRows } = await supabase
    .from("post_analytics")
    .select("views")
    .eq("user_id", sp.user_id)
    .gte("created_at", since);
  const avgList = (avgRows ?? []) as any[];
  const userAvg = avgList.length
    ? avgList.reduce((s, a) => s + (a.views ?? 0), 0) / avgList.length
    : 0;

  let performance: "high" | "low" | "unknown" = "unknown";
  let recommendation: string | null = null;
  if (avgList.length >= 3 && views > 0) {
    if (views >= userAvg * 1.1) {
      performance = "high";
      recommendation = `Reuse ${visualStyle ?? "this visual"} + ${voiceTone ?? "this voice"} for next ${sp.city} job — outperformed avg by ${Math.round(((views - userAvg) / Math.max(userAvg, 1)) * 100)}%.`;
    } else if (views <= userAvg * 0.9) {
      performance = "low";
      recommendation = `Avoid ${visualStyle ?? "this visual"}/${voiceTone ?? "this voice"} combo — underperformed by ${Math.round(((userAvg - views) / Math.max(userAvg, 1)) * 100)}%. Force a variation next run.`;
    } else {
      performance = "unknown";
      recommendation = "On-par with average — no strong signal.";
    }
  } else {
    recommendation = "Not enough baseline data to classify yet.";
  }

  await supabase.from("pipeline_reflections").insert({
    user_id: sp.user_id,
    city: sp.city,
    scheduled_post_id: sp.id,
    job_id: job.id,
    visual_style: visualStyle,
    voice_tone: voiceTone,
    hook_type: hookType,
    views: Math.round(views),
    engagement: Math.round(engagement),
    user_avg_views: userAvg,
    performance,
    recommendation,
  });

  await log(`Reflection: ${performance} (${Math.round(views)} vs avg ${Math.round(userAvg)})`, {
    visual_style: visualStyle,
    voice_tone: voiceTone,
    hook_type: hookType,
  });

  return {
    output: { performance, views: Math.round(views), user_avg_views: userAvg },
    done: true,
  };
};

export const handlers: Record<JobType, JobHandler> = {
  generate_content: generateContent,
  generate_voice: generateVoice,
  render_video: renderVideo,
  publish_post: publishPost,
  analyze_performance: analyzePerformance,
};
